ALTER TABLE "AcquisitionCampaign"
ADD COLUMN "cacAutoPausePctOfTarget" DOUBLE PRECISION NOT NULL DEFAULT 1.25,
ADD COLUMN "minLtvCacRatio" DOUBLE PRECISION NOT NULL DEFAULT 2.5,
ADD COLUMN "approvalCapPct" DOUBLE PRECISION NOT NULL DEFAULT 0.15;
